# Generated by Django 4.2.25 on 2025-10-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('ozet', models.TextField(blank=True, verbose_name='Özet')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('yayin_tarihi', models.DateTimeField(verbose_name='Yayın Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('yayinda', models.BooleanField(default=False, verbose_name='Yayında')),
                ('word_dosyasi', models.FileField(blank=True, null=True, upload_to='duyurular/word/%Y/%m/%d/', verbose_name='Word Belgesi')),
                ('pdf_dosyasi', models.FileField(blank=True, null=True, upload_to='duyurular/pdf/%Y/%m/%d/', verbose_name='PDF Belgesi')),
                ('excel_dosyasi', models.FileField(blank=True, null=True, upload_to='duyurular/excel/%Y/%m/%d/', verbose_name='Excel Dosyası')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-yayin_tarihi'],
            },
        ),
    ]
