# Generated by Django 4.2.25 on 2025-10-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0002_remove_duyuru_excel_dosyasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='fakulte',
            field=models.CharField(choices=[('LEE', 'LEE'), ('FEF', 'FEF'), ('IIBF', 'IIBF'), ('MMF', 'MMF'), ('SBF', 'SBF'), ('ILTF', 'ILTF'), ('SPOR', 'SPOR'), ('UBY', 'UBY'), ('MYO', 'MYO'), ('SHMYO', 'SHMYO'), ('GENEL', 'Genel Duyuru')], default='GENEL', max_length=10, verbose_name='Fakülte/Bölüm'),
        ),
        migrations.AddIndex(
            model_name='duyuru',
            index=models.Index(fields=['fakulte', 'yayinda', 'yayin_tarihi'], name='duyurular_d_fakulte_74b8bb_idx'),
        ),
    ]
