# Generated by Django 4.2.25 on 2025-10-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0003_duyuru_fakulte_duyuru_duyurular_d_fakulte_74b8bb_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Bölüm Adı')),
                ('kod', models.SlugField(unique=True, verbose_name='Bölüm Kodu')),
                ('fakulte', models.CharField(choices=[('LEE', 'LEE'), ('FEF', 'FEF'), ('IIBF', 'IIBF'), ('MMF', 'MMF'), ('SBF', 'SBF'), ('ILTF', 'ILTF'), ('SPOR', 'SPOR'), ('UBY', 'UBY'), ('MYO', 'MYO'), ('SHMYO', 'SHMYO'), ('GENEL', 'Genel Duyuru')], max_length=10, verbose_name='Bağlı Fakülte')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
                'ordering': ['fakulte', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='duyuru',
            name='bolumler',
            field=models.ManyToManyField(blank=True, help_text='Bu duyurunun gösterileceği bölümleri seçin', to='duyurular.bolum', verbose_name='İlgili Bölümler'),
        ),
    ]
