# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0004_bolum_duyuru_bolumler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='ad_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='ad_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='ad_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='ad_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='ad_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='ad_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='baslik_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='baslik_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='baslik_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='baslik_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='baslik_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='baslik_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='icerik_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='icerik_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='icerik_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='icerik_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='icerik_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='icerik_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ozet_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ozet_de',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ozet_en',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ozet_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ozet_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='ozet_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='duyurudosya',
            name='aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='duyurudosya',
            name='aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='duyurudosya',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='duyurudosya',
            name='aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='duyurudosya',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='duyurudosya',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
