# Generated by Django 6.0 on 2026-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adalet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaletetkinlik',
            name='kayit_gerekiyor',
            field=models.BooleanField(default=False, verbose_name='Kayıت Gerekiyor'),
        ),
    ]
