# Generated by Django 6.0 on 2026-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='afis',
            field=models.ImageField(blank=True, help_text='Önerilen boyut: Genişlik maksimum 1200px, yükseklik serbest. Posterin tamamı görünecektir.', null=True, upload_to='etkinlikler/afis/%Y/%m/%d/', verbose_name='Etkinlik Afişi'),
        ),
    ]
