# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0002_alter_etkinlik_afis'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='baslik_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='baslik_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='baslik_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='baslik_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='baslik_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='baslik_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='detayli_aciklama_ar',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='detayli_aciklama_de',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='detayli_aciklama_en',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='detayli_aciklama_fa',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='detayli_aciklama_ru',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='detayli_aciklama_tr',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='kisa_aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='kisa_aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='kisa_aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='kisa_aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='kisa_aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='kisa_aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
    ]
