# Generated by Django 6.0 on 2026-01-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saglik_hizmetleri_myo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saglikhizmetlerimyoduyuru',
            name='kategori',
            field=models.CharField(choices=[('akademik', 'Akademik'), ('etkinlik', 'Etkinlik'), ('ogrenci', 'Öğrenci'), ('genel', 'Genel')], default='genel', max_length=20, verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='SaglikHizmetleriMYODosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='saglik_hizmetleri_myo/dosyalar/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(blank=True, max_length=255, verbose_name='Dosya Adı')),
                ('tur', models.CharField(choices=[('word', 'Word Belgesi'), ('pdf', 'PDF Belgesi'), ('excel', 'Excel Dosyası'), ('resim', 'Resim'), ('arsiv', 'Arşiv Dosyası'), ('diger', 'Diğer')], default='diger', max_length=10, verbose_name='Dosya Türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('duyuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='saglik_hizmetleri_myo.saglikhizmetlerimyoduyuru', verbose_name='Duyuru')),
            ],
            options={
                'verbose_name': 'Sağlık Hizmetleri MYO Dosyası',
                'verbose_name_plural': 'Sağlık Hizmetleri MYO Dosyaları',
                'ordering': ['tur', 'dosya_adi'],
            },
        ),
    ]
