# Generated by Django 4.2.25 on 2025-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektrik_elektronik_muhendisligi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersprogramidosyaee',
            name='sinif',
            field=models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıف'), ('tum', 'Tüm Sınıflar'), ('lisansustu', 'Lisansüstü')], default='1', max_length=15, verbose_name='Sınıf'),
        ),
    ]
