# Generated by Django 6.0 on 2026-01-13 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0004_bolum_duyuru_bolumler'),
        ('gida_muhendisligi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GidaDersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari/gida/', verbose_name='Dosya')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('yuksek_lisans', 'Yüksek Lisans'), ('doktora', 'Doktora'), ('tum', 'Tüm Sınıflar')], max_length=20, verbose_name='Sınıf/Düzey')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı (Gıda Mühendisliği)',
                'verbose_name_plural': 'Ders Programları (Gıda Mühendisliği)',
                'ordering': ['-yayin_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='DersProgramiDosyaGida',
        ),
        migrations.DeleteModel(
            name='GidaDuyuru',
        ),
        migrations.CreateModel(
            name='GidaMuhendisligiDuyuru',
            fields=[
            ],
            options={
                'verbose_name': 'Gıda Mühendisliği Duyurusu',
                'verbose_name_plural': 'Gıda Mühendisliği Duyuruları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('duyurular.duyuru',),
        ),
        migrations.AlterModelOptions(
            name='gida_etkinlik',
            options={'ordering': ['baslangic_tarihi'], 'verbose_name': 'Etkinlik (Gıda Mühendisliği)', 'verbose_name_plural': 'Etkinlikler (Gıda Mühendisliği)'},
        ),
        migrations.AlterField(
            model_name='gida_etkinlik',
            name='afis',
            field=models.ImageField(blank=True, null=True, upload_to='etkinlikler/gida_afis/%Y/%m/%d/', verbose_name='Etkinlik Afişi'),
        ),
        migrations.AlterField(
            model_name='gida_etkinlik',
            name='etkinlik_turu',
            field=models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('tanitim', 'Tanıtım Günleri'), ('workshop', 'Workshop / Atölye'), ('laboratuvar', 'Laboratuvar Çalışması'), ('saha_gezisi', 'Saha Gezisi'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü'),
        ),
        migrations.AlterField(
            model_name='gida_etkinlik',
            name='kayit_gerekiyor',
            field=models.BooleanField(default=False, verbose_name='Kayıت Gerekiyor'),
        ),
    ]
