# Generated by Django 6.0 on 2026-01-02 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duyurular', '0004_bolum_duyuru_bolumler'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeeDuyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('ozet', models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', verbose_name='Özet')),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('etkinlik', 'Etkinlik'), ('ogrenci', 'Öğrenci'), ('genel', 'Genel')], default='genel', max_length=20, verbose_name='Kategori')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='lee/duyurular/', verbose_name='Dosya Eki')),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında')),
                ('onemli', models.BooleanField(default=False, verbose_name='Önemli Duyuru')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('ana_duyuru', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lee_duyuru', to='duyurular.duyuru', verbose_name='Ana Duyuru')),
            ],
            options={
                'verbose_name': 'Lee Duyurusu',
                'verbose_name_plural': 'Lee Duyuruları',
                'ordering': ['-onemli', '-yayin_tarihi', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='LeeDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='lee_edebiyat/dosyalar/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(blank=True, max_length=255, verbose_name='Dosya Adı')),
                ('tur', models.CharField(choices=[('word', 'Word Belgesi'), ('pdf', 'PDF Belgesi'), ('excel', 'Excel Dosyası'), ('resim', 'Resim'), ('arsiv', 'Arşiv Dosyası'), ('diger', 'Diğer')], default='diger', max_length=10, verbose_name='Dosya Türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('duyuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='lee.leeduyuru', verbose_name='Duyuru')),
            ],
            options={
                'verbose_name': 'Lee Edebiyat Dosyası',
                'verbose_name_plural': 'Lee Edebiyat Dosyaları',
                'ordering': ['tur', 'dosya_adi'],
            },
        ),
    ]
