# Generated by Django 6.0 on 2026-01-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lee', '0002_lee_etkinlik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leedosya',
            options={'ordering': ['tur', 'dosya_adi'], 'verbose_name': 'LEE Dosyası', 'verbose_name_plural': 'LEE Dosyaları'},
        ),
        migrations.AlterModelOptions(
            name='leeduyuru',
            options={'ordering': ['-onemli', '-yayin_tarihi', 'sira'], 'verbose_name': 'LEE Duyurusu', 'verbose_name_plural': 'LEE Duyuruları'},
        ),
        migrations.AlterField(
            model_name='leedosya',
            name='dosya',
            field=models.FileField(upload_to='lee/dosyalar/%Y/%m/%d/', verbose_name='Dosya'),
        ),
    ]
