# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lee', '0003_alter_leedosya_options_alter_leeduyuru_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lee_etkinlik',
            name='baslik_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='baslik_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='baslik_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='baslik_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='baslik_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='baslik_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='detayli_aciklama_ar',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='detayli_aciklama_de',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='detayli_aciklama_en',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='detayli_aciklama_fa',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='detayli_aciklama_ru',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='detayli_aciklama_tr',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='kisa_aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='kisa_aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='kisa_aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='kisa_aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='kisa_aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='lee_etkinlik',
            name='kisa_aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='leedosya',
            name='aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='leedosya',
            name='aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='leedosya',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='leedosya',
            name='aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='leedosya',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='leedosya',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='baslik_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='baslik_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='baslik_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='baslik_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='baslik_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='baslik_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='icerik_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='icerik_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='icerik_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='icerik_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='icerik_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='icerik_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='ozet_ar',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='ozet_de',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='ozet_en',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='ozet_fa',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='ozet_ru',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='leeduyuru',
            name='ozet_tr',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
    ]
