# Generated by Django 6.0 on 2026-02-16 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Geçerli bir telefon numarası giriniz.', regex='^[0-9\\-\\+\\s\\(\\)]{10,20}$')], verbose_name='Telefon Numarası')),
                ('accept_communication', models.BooleanField(default=False, verbose_name='İletişim İzni')),
                ('accept_kvkk', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('is_processed', models.BooleanField(default=False, verbose_name='İşlendi mi?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
            ],
            options={
                'verbose_name': 'Geri Arama Talebi',
                'verbose_name_plural': 'Geri Arama Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
