# Generated by Django 6.0 on 2025-12-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_content_ar_news_content_de_news_content_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='تصویر اصلی'),
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/attachments/%Y/%m/%d/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('image', 'Image'), ('other', 'Other')], max_length=10, verbose_name='نوع فایل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.news')),
            ],
            options={
                'verbose_name': 'فایل پیوست',
                'verbose_name_plural': 'فایل\u200cهای پیوست',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/%Y/%m/%d/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='عنوان تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'verbose_name': 'تصویر خبر',
                'verbose_name_plural': 'تصاویر خبر',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
