# Generated by Django 6.0 on 2025-12-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options_remove_news_image_news_main_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsattachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'فایل پیوست', 'verbose_name_plural': 'Attached files'},
        ),
    ]
