# Generated by Django 6.0 on 2025-12-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsattachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'خبر', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'تصویر خبر', 'verbose_name_plural': 'News images'},
        ),
    ]
