# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_options_alter_newsimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='summary_ar',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_de',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_fa',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_tr',
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان فایل'),
        ),
    ]
