# Generated by Django 4.2.25 on 2025-10-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='content_type',
            field=models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=10, verbose_name='نوع محتوا'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slider/videos/', verbose_name='فایل ویدیو'),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='لینک ویدیو (YouTube, Vimeo, etc.)'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='تصویر'),
        ),
    ]
