# Generated by Django 6.0 on 2025-12-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_content_ar_page_content_de_page_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='title_fr',
        ),
    ]
