# Generated by Django 6.0 on 2026-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='content_type',
            field=models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], default='image', max_length=10, verbose_name='İçerik Türü'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slider/videos/', verbose_name='Video Dosyası'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video Linki (YouTube, Vimeo, vs.)'),
        ),
    ]
