# Generated by Django 6.0 on 2026-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekreasyon', '0002_rekreasyondersprogrami_rekreasyonetkinlik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekreasyonetkinlik',
            name='afis',
            field=models.ImageField(blank=True, null=True, upload_to='etkinlikler/afis/rekreasyon/%Y/%m/%d/', verbose_name='Etkinlik Afişi'),
        ),
        migrations.AlterField(
            model_name='rekreasyonetkinlik',
            name='etkinlik_turu',
            field=models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('tanitim', 'Tanıtım Günleri'), ('workshop', 'Workshop / Atölye'), ('sergi', 'Sergi'), ('yarisma', 'Yarışma'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü'),
        ),
    ]
