# Generated by Django 6.0 on 2026-02-23 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('summary', models.TextField(blank=True, help_text='Listelerde gösterilecek kısa özet', max_length=300, verbose_name='Özet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sks/announcements/%Y/%m/', verbose_name='Görsel')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Dış Link')),
                ('external_link_text', models.CharField(blank=True, max_length=50, verbose_name='Dış Link Metni')),
                ('announcement_date', models.DateField(default=django.utils.timezone.now, verbose_name='Duyuru Tarihi')),
                ('is_important', models.BooleanField(default=False, verbose_name='Önemli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-is_important', '-announcement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('news_type', models.CharField(choices=[('news', 'Haber'), ('announcement', 'Duyuru'), ('event', 'Etkinlik'), ('achievement', 'Başarı')], default='news', max_length=20, verbose_name='Haber Türü')),
                ('image', models.ImageField(blank=True, help_text='Haber ana görseli (Önerilen boyut: 800x400 piksel)', null=True, upload_to='sks/news/%Y/%m/', verbose_name='Görsel')),
                ('image_alt', models.CharField(blank=True, help_text='SEO ve erişilebilirlik için', max_length=255, verbose_name='Görsel Alternatif Metni')),
                ('summary', models.TextField(help_text='Kartlarda gösterilecek kısa özet (Maksimum 500 karakter)', max_length=500, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Haberin yayınlanma zamanı', verbose_name='Yayın Tarihi')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('author', models.CharField(blank=True, help_text='Yazar adı veya haber kaynağı', max_length=100, verbose_name='Yazar')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='sks.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-is_featured', '-published_at'],
                'indexes': [models.Index(fields=['-published_at', 'is_published'], name='sks_news_publish_472dc4_idx'), models.Index(fields=['news_type', 'is_published'], name='sks_news_news_ty_1e272a_idx')],
            },
        ),
    ]
