# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sks', '0002_announcement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=250, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=250, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=250, null=True, verbose_name='Başlık'),
        ),
    ]
