# Generated by Django 4.2.25 on 2025-11-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/categories/', verbose_name='Kapak Görseli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
            ],
            options={
                'verbose_name': 'Galeri Kategorisi',
                'verbose_name_plural': 'Galeri Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='gallery/images/', verbose_name='Görsel')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerycategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ['order', '-upload_date'],
            },
        ),
    ]
