# Generated by Django 4.2.25 on 2025-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BAPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Proje Başlığı')),
                ('coordinator', models.CharField(max_length=200, verbose_name='Koordinatör')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Bütçe')),
                ('status', models.CharField(choices=[('ongoing', 'Devam Ediyor'), ('completed', 'Tamamlandı')], max_length=20)),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BAP Projesi',
                'verbose_name_plural': 'BAP Projeleri',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Laboratuvar Adı')),
                ('faculty', models.CharField(max_length=150, verbose_name='Fakülte/Bölüm')),
                ('director', models.CharField(max_length=200, verbose_name='Sorumlu Öğretim Üyesi')),
                ('equipment', models.TextField(verbose_name='Ekipmanlar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laboratuvar',
                'verbose_name_plural': 'Laboratuvarlar',
            },
        ),
        migrations.CreateModel(
            name='ResearchPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('commission', models.CharField(max_length=400, verbose_name='Komisyon')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Araştırma Politikası',
                'verbose_name_plural': 'Araştırma Politikaları',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
