# Generated by Django 4.2.25 on 2025-11-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arastirma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Ödül Adı')),
                ('award_type', models.CharField(choices=[('international', 'Uluslararası Ödül'), ('national', 'Ulusal Ödül'), ('tubitak', 'TÜBİTAK Ödülü'), ('patent', 'Patent Ödülü'), ('young_researcher', 'Genç Araştırmacı Ödülü'), ('industry', 'Sanayi İşbirliği Ödülü'), ('conference', 'Konferans Ödülü')], max_length=50, verbose_name='Ödül Türü')),
                ('recipient', models.CharField(max_length=200, verbose_name='Ödül Alan')),
                ('faculty', models.CharField(max_length=150, verbose_name='Fakülte/Bölüm')),
                ('awarding_organization', models.CharField(max_length=300, verbose_name='Veren Kuruluş')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Kategori')),
                ('award_date', models.DateField(verbose_name='Ödül Tarihi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ödül Miktarı')),
                ('project_title', models.CharField(blank=True, max_length=400, verbose_name='Proje Başlığı')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ödül',
                'verbose_name_plural': 'Ödüller',
                'ordering': ['-award_date'],
            },
        ),
        migrations.CreateModel(
            name='IntellectualProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Başlık')),
                ('property_type', models.CharField(choices=[('patent', 'Patent'), ('utility_model', 'Faydalı Model'), ('trademark', 'Ticari Marka'), ('copyright', 'Telif Hakkı'), ('industrial_design', 'Endüstriyel Tasarım')], max_length=50, verbose_name='Mülkiyet Türü')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Tescil Numarası')),
                ('inventor', models.CharField(max_length=200, verbose_name='Mucit/Sahip')),
                ('faculty', models.CharField(max_length=150, verbose_name='Fakülte/Bölüm')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('approved', 'Onaylı'), ('application', 'Başvuru Sürecinde'), ('rejected', 'Reddedildi'), ('expired', 'Süresi Dolmuş')], max_length=20, verbose_name='Durum')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Başvuru Tarihi')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Tescil Tarihi')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('is_international', models.BooleanField(default=False, verbose_name='Uluslararası')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fikri Mülkiyet',
                'verbose_name_plural': 'Fikri Mülkiyetler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Merkez Adı')),
                ('director', models.CharField(max_length=200, verbose_name='Müdür')),
                ('faculty', models.CharField(max_length=150, verbose_name='Bağlı Fakülte')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('research_areas', models.TextField(verbose_name='Araştırma Alanları')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('planning', 'Planlama Aşamasında'), ('inactive', 'Pasif')], default='active', max_length=20)),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Kuruluş Tarihi')),
                ('researcher_count', models.PositiveIntegerField(default=0, verbose_name='Araştırmacı Sayısı')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Araştırma Merkezi',
                'verbose_name_plural': 'Araştırma Merkezleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Başlık')),
                ('output_type', models.CharField(choices=[('sci_article', 'SCI Makale'), ('international_article', 'Uluslararası Makale'), ('national_article', 'Ulusal Makale'), ('book', 'Kitap'), ('book_chapter', 'Kitap Bölümü'), ('conference_paper', 'Konferans Bildirisi'), ('report', 'Rapor')], max_length=50, verbose_name='Çıktı Türü')),
                ('authors', models.TextField(verbose_name='Yazarlar')),
                ('journal', models.CharField(blank=True, max_length=300, verbose_name='Dergi/Kitap')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Yayınevi')),
                ('publication_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Cilt')),
                ('issue', models.CharField(blank=True, max_length=50, verbose_name='Sayı')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='Sayfalar')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('issn_isbn', models.CharField(blank=True, max_length=50, verbose_name='ISSN/ISBN')),
                ('abstract', models.TextField(blank=True, verbose_name='Özet')),
                ('citation_count', models.PositiveIntegerField(default=0, verbose_name='Atıf Sayısı')),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Etki Faktörü')),
                ('quartile', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, verbose_name='Kuartil')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Araştırma Çıktısı',
                'verbose_name_plural': 'Araştırma Çıktıları',
                'ordering': ['-publication_date'],
            },
        ),
    ]
