# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arastirma', '0002_award_intellectualproperty_researchcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='title_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='Ödül Adı'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Ödül Adı'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Ödül Adı'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_fa',
            field=models.CharField(max_length=400, null=True, verbose_name='Ödül Adı'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Ödül Adı'),
        ),
        migrations.AddField(
            model_name='award',
            name='title_tr',
            field=models.CharField(max_length=400, null=True, verbose_name='Ödül Adı'),
        ),
        migrations.AddField(
            model_name='bapproject',
            name='title_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='Proje Başlığı'),
        ),
        migrations.AddField(
            model_name='bapproject',
            name='title_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Proje Başlığı'),
        ),
        migrations.AddField(
            model_name='bapproject',
            name='title_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Proje Başlığı'),
        ),
        migrations.AddField(
            model_name='bapproject',
            name='title_fa',
            field=models.CharField(max_length=400, null=True, verbose_name='Proje Başlığı'),
        ),
        migrations.AddField(
            model_name='bapproject',
            name='title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Proje Başlığı'),
        ),
        migrations.AddField(
            model_name='bapproject',
            name='title_tr',
            field=models.CharField(max_length=400, null=True, verbose_name='Proje Başlığı'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='title_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='title_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='title_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='title_fa',
            field=models.CharField(max_length=400, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='title_tr',
            field=models.CharField(max_length=400, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='title_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='title_de',
            field=models.CharField(max_length=500, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='title_fa',
            field=models.CharField(max_length=500, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchoutput',
            name='title_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='content_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='content_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='title_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='title_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='researchpolicy',
            name='title_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
    ]
