# Generated by Django 6.0 on 2026-01-13 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0004_bolum_duyuru_bolumler'),
        ('egzersiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgzersizDersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari/egzersiz/', verbose_name='Dosya')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('tum', 'Tüm Sınıflar')], max_length=10, verbose_name='Sınıf')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı (Egzersiz)',
                'verbose_name_plural': 'Ders Programları (Egzersiz)',
                'ordering': ['-yayin_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='EgzersizEtkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Etkinlik Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('kisa_aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('detayli_aciklama', models.TextField(verbose_name='Detaylı Açıklama')),
                ('etkinlik_turu', models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('yarisma', 'Yarışma / Turnuva'), ('workshop', 'Workshop / Atölye'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('yer', models.CharField(max_length=255, verbose_name='Etkinlik Yeri')),
                ('afis', models.ImageField(blank=True, null=True, upload_to='etkinlikler/afis/egzersiz/%Y/%m/%d/', verbose_name='Etkinlik Afişi')),
                ('katilim_linki', models.URLField(blank=True, verbose_name='Katılım Linki')),
                ('kayit_gerekiyor', models.BooleanField(default=False, verbose_name='Kayıt Gerekiyor')),
                ('ucretli', models.BooleanField(default=False, verbose_name='Ücretli Etkinlik')),
                ('yayinda', models.BooleanField(default=False, verbose_name='Yayında')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etkinlik (Egzersiz)',
                'verbose_name_plural': 'Etkinlikler (Egzersiz)',
                'ordering': ['baslangic_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='DersProgramiDosyaSporBilimleri',
        ),
        migrations.DeleteModel(
            name='SporBilimleri_Etkinlik',
        ),
        migrations.DeleteModel(
            name='SporBilimleriDuyuru',
        ),
        migrations.CreateModel(
            name='EgzersizDuyuru',
            fields=[
            ],
            options={
                'verbose_name': 'Egzersiz Duyurusu',
                'verbose_name_plural': 'Egzersiz Duyuruları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('duyurular.duyuru',),
        ),
    ]
