# Generated by Django 6.0 on 2026-02-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egzersiz', '0002_egzersizdersprogrami_egzersizetkinlik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egzersizetkinlik',
            name='etkinlik_turu',
            field=models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('tanitim', 'Tanıtım Günleri'), ('workshop', 'Workshop / Atölye'), ('sergi', 'Sergi'), ('yarisma', 'Yarışma'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü'),
        ),
    ]
