# Generated by Django 6.0 on 2026-01-09 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingiliz_dili_edebiyati', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ing_DersProgramiDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Dosya Başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari/ingiliz_dili_edebiyati/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_turu', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('resim', 'Resim'), ('diger', 'Diğer')], default='pdf', max_length=10, verbose_name='Dosya Türü')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('tum', 'Tüm Sınıflar'), ('lisansustu', 'Lisansüstü')], default='1', max_length=15, verbose_name='Sınıf')),
                ('akademik_yil', models.CharField(default='2024-2025', max_length=9, verbose_name='Akademik Yıl')),
                ('yayin_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı Dosyası (İngiliz Dili ve Edebiyatı)',
                'verbose_name_plural': 'Ders Programı Dosyaları (İngiliz Dili ve Edebiyatı)',
                'ordering': ['sira', '-yayin_tarihi'],
            },
        ),
        migrations.RenameModel(
            old_name='IDE_Etkinlik',
            new_name='Ing_Etkinlik',
        ),
        migrations.DeleteModel(
            name='IDEDersProgramiDosya',
        ),
        migrations.AlterModelOptions(
            name='ing_etkinlik',
            options={'ordering': ['baslangic_tarihi'], 'verbose_name': 'Etkinlik (İngiliz Dili ve Edebiyatı)', 'verbose_name_plural': 'Etkinlikler (İngiliz Dili ve Edebiyatı)'},
        ),
    ]
