# Generated by Django 6.0 on 2026-01-12 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingiliz_dili_edebiyati', '0002_ing_dersprogramidosya_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari/', verbose_name='Dosya')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('tum', 'Tüm Sınıflar')], max_length=10, verbose_name='Sınıf')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı',
                'verbose_name_plural': 'Ders Programları',
                'ordering': ['-yayin_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='Ing_DersProgramiDosya',
        ),
    ]
