# Generated by Django 6.0 on 2026-08-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingiliz_dili_edebiyati', '0003_dersprogrami_delete_ing_dersprogramidosya'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngilizDiliEdebiyatiFaaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=300, verbose_name='Faaliyet Başlığı')),
                ('tarih', models.CharField(blank=True, max_length=100, verbose_name='Tarih / Dönem')),
                ('icerik', models.TextField(blank=True, verbose_name='İçerik')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Faaliyet (Ingiliz Dili Edebiyati)',
                'verbose_name_plural': 'Faaliyetler (Ingiliz Dili Edebiyati)',
                'ordering': ['sira', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IngilizDiliEdebiyatiFaaliyetGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)')),
                ('faaliyet_turu', models.CharField(choices=[('idari', 'İdari Faaliyetler'), ('diger', 'Diğer Faaliyetler')], max_length=10, verbose_name='Faaliyet Türü')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Faaliyet Grubu (Ingiliz Dili Edebiyati)',
                'verbose_name_plural': 'Faaliyet Grupları (Ingiliz Dili Edebiyati)',
                'ordering': ['sira', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IngilizDiliEdebiyatiFaaliyetGorseli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(upload_to='faaliyetler/ingiliz_dili_edebiyati/', verbose_name='Görsel')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('faaliyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorseller', to='ingiliz_dili_edebiyati.ingilizdiliedebiyatifaaliyet', verbose_name='Faaliyet')),
            ],
            options={
                'verbose_name': 'Faaliyet Görseli (Ingiliz Dili Edebiyati)',
                'verbose_name_plural': 'Faaliyet Görselleri (Ingiliz Dili Edebiyati)',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ingilizdiliedebiyatifaaliyet',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faaliyetler', to='ingiliz_dili_edebiyati.ingilizdiliedebiyatifaaliyetgrubu', verbose_name='Faaliyet Grubu'),
        ),
    ]
