# Generated by Django 6.0 on 2025-12-30 13:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('tc_number', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('program', models.CharField(max_length=200, verbose_name='Kazandığınız Bölüm/Program')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banka Adı')),
                ('card_number', models.CharField(max_length=20, verbose_name='Kart Numarası')),
                ('card_expiry', models.CharField(max_length=7, verbose_name='Son Kullanma Tarihi')),
                ('card_cvc', models.CharField(max_length=4, verbose_name='CVC Kodu')),
                ('payment_method', models.CharField(choices=[('full', 'Ücretin tamamını kredi kartından tek çekim istiyorum.'), ('partial_installment', "1/3'ünü Kredi Kartına Tek Çekim kalan 2/3'ünü Kredi Kartına Taksit İstiyorum"), ('cash_installment', "1/3'ünü Bankaya nakit yatırdım kalan 2/3'ünü Kredi Kartına Taksit İstiyorum"), ('proforma', "1/3'ünü Bankaya nakit yatırdım kalan 2/3'ünü Proforma Fatura Yöntemi ile Ödemek İstiyorum")], max_length=50, verbose_name='Ödeme Yöntemi')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='online_payments/receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Ödeme Dekontu')),
                ('yks_result', models.FileField(upload_to='online_payments/yks_results/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='YKS Sonuç Belgesi')),
                ('proforma_name', models.CharField(blank=True, max_length=200, verbose_name='Proforma Ad Soyad')),
                ('proforma_tc', models.CharField(blank=True, max_length=11, verbose_name='Proforma TC No')),
                ('card_approval', models.BooleanField(default=False, verbose_name='Kart Onayı')),
                ('kvkk_approval', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('is_processed', models.BooleanField(default=False, verbose_name='İşlendi')),
                ('payment_status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Ödeme Durumu')),
                ('payment_reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Ödeme Referans Kodu')),
            ],
            options={
                'verbose_name': 'Online Ödeme',
                'verbose_name_plural': 'Online Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('tc_number', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('program', models.CharField(max_length=200, verbose_name='Kazandığınız Fakülte/Bölüm')),
                ('diploma', models.FileField(upload_to='online_registrations/diplomas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Lise Diploması')),
                ('id_card', models.FileField(upload_to='online_registrations/id_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Nüfus Cüzdanı')),
                ('yks_result', models.FileField(upload_to='online_registrations/yks_results/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='YKS Sonuç Belgesi')),
                ('health_report', models.FileField(blank=True, null=True, upload_to='online_registrations/health_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Sağlık Raporu')),
                ('payment_receipt', models.FileField(upload_to='online_registrations/payment_receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Ödeme Dekontu')),
                ('registration_declaration', models.BooleanField(default=False, verbose_name='Kayıt ve Evrak Teslim Beyanı')),
                ('declaration_acceptance', models.BooleanField(default=False, verbose_name='Beyanname Kabulü')),
                ('contract_acceptance', models.BooleanField(default=False, verbose_name='Sözleşme Kabulü')),
                ('kvkk_approval', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('is_processed', models.BooleanField(default=False, verbose_name='İşlendi')),
                ('registration_status', models.CharField(choices=[('pending', 'Bekliyor'), ('under_review', 'İnceleniyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Kayıt Durumu')),
                ('registration_reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Kayıt Referans Kodu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Online Kayıt',
                'verbose_name_plural': 'Online Kayıtlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
