# Generated by Django 6.0 on 2025-12-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci_isleri', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlinePayment',
        ),
        migrations.DeleteModel(
            name='OnlineRegistration',
        ),
    ]
