# Generated by Django 4.2.25 on 2025-10-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0003_duyuru_fakulte_duyuru_duyurular_d_fakulte_74b8bb_idx'),
        ('iktisadi_idari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IktisadiIdariDuyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('ozet', models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', verbose_name='Özet')),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('etkinlik', 'Etkinlik'), ('ogrenci', 'Öğrenci'), ('staj', 'Staj'), ('mezun', 'Mezun'), ('genel', 'Genel')], default='genel', max_length=20, verbose_name='Kategori')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='iktisadi_idari/duyurular/', verbose_name='Dosya Eki')),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında')),
                ('onemli', models.BooleanField(default=False, verbose_name='Önemli Duyuru')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('ana_duyuru', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iktisadi_idari_duyuru', to='duyurular.duyuru', verbose_name='Ana Duyuru')),
            ],
            options={
                'verbose_name': 'İktisadi İdari Duyurusu',
                'verbose_name_plural': 'İktisadi İdari Duyuruları',
                'ordering': ['-onemli', '-yayin_tarihi', 'sira'],
            },
        ),
        migrations.RemoveField(
            model_name='i̇ktisadii̇dariduyuru',
            name='ana_duyuru',
        ),
        migrations.DeleteModel(
            name='İktisadiİdariDosya',
        ),
        migrations.DeleteModel(
            name='İktisadiİdariDuyuru',
        ),
    ]
