# Generated by Django 4.2.25 on 2025-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FenEdebiyatDuyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('ozet', models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', verbose_name='Özet')),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('etkinlik', 'Etkinlik'), ('ogrenci', 'Öğrenci'), ('genel', 'Genel')], default='genel', max_length=20, verbose_name='Kategori')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='fen_edebiyat/duyurular/', verbose_name='Dosya Eki')),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında')),
                ('onemli', models.BooleanField(default=False, verbose_name='Önemli Duyuru')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Fen Edebiyat Duyurusu',
                'verbose_name_plural': 'Fen Edebiyat Duyuruları',
                'ordering': ['-onemli', '-yayin_tarihi', 'sira'],
            },
        ),
    ]
