# Generated by Django 4.2.25 on 2025-10-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0003_duyuru_fakulte_duyuru_duyurular_d_fakulte_74b8bb_idx'),
        ('fen_edebiyat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenedebiyatduyuru',
            name='ana_duyuru',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fen_edebiyat_duyuru', to='duyurular.duyuru', verbose_name='Ana Duyuru'),
        ),
    ]
