# Generated by Django 6.0 on 2026-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default='test@university.local', max_length=254),
            preserve_default=False,
        ),
    ]
