# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_tag_importantlink_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlink',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='importantlink',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
