# Generated by Django 6.0 on 2026-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimduyuru',
            name='kategori',
            field=models.CharField(choices=[('akademik', 'Akademik'), ('etkinlik', 'Etkinlik'), ('ogrenci', 'Öğrenci'), ('genel', 'Genel')], default='genel', max_length=20, verbose_name='Kategori'),
        ),
    ]
