# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0002_alter_iletisimduyuru_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisimduyuru',
            name='baslik_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='baslik_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='baslik_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='baslik_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='baslik_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='baslik_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='icerik_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='icerik_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='icerik_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='icerik_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='icerik_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='icerik_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='ozet_ar',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='ozet_de',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='ozet_en',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='ozet_fa',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='ozet_ru',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='iletisimduyuru',
            name='ozet_tr',
            field=models.TextField(blank=True, help_text='Kısa özet (opsiyonel)', null=True, verbose_name='Özet'),
        ),
    ]
