# Generated by Django 6.0 on 2026-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('country', models.CharField(choices=[('tr', 'Turkey'), ('us', 'United States'), ('gb', 'United Kingdom'), ('de', 'Germany'), ('fr', 'France')], max_length=5, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('program', models.CharField(choices=[('computer', 'Computer Engineering'), ('business', 'Business Administration'), ('medicine', 'Medicine'), ('law', 'Law'), ('architecture', 'Architecture')], max_length=20, verbose_name='Desired Program')),
                ('semester', models.CharField(choices=[('fall2024', 'Fall 2024'), ('spring2025', 'Spring 2025'), ('fall2025', 'Fall 2025')], max_length=20, verbose_name='Start Date')),
                ('education_level', models.CharField(choices=[('highschool', 'High School Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], max_length=20, verbose_name='Education Level')),
                ('english_level', models.CharField(blank=True, choices=[('beginner', 'Beginner (A1-A2)'), ('intermediate', 'Intermediate (B1-B2)'), ('advanced', 'Advanced (C1-C2)'), ('native', 'Native Speaker')], max_length=20, null=True, verbose_name='English Proficiency')),
                ('passport_copy', models.FileField(upload_to='international/applications/passports/%Y/%m/%d/', verbose_name='Passport Copy')),
                ('diploma_certificate', models.FileField(upload_to='international/applications/diplomas/%Y/%m/%d/', verbose_name='Diploma/Certificate')),
                ('academic_transcript', models.FileField(upload_to='international/applications/transcripts/%Y/%m/%d/', verbose_name='Academic Transcript')),
                ('passport_photo', models.FileField(upload_to='international/applications/photos/%Y/%m/%d/', verbose_name='Passport Photo')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='Newsletter Subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'International Application',
                'verbose_name_plural': 'International Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
