# Generated by Django 6.0 on 2026-01-13 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebelik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbelikDersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari/ebelik/', verbose_name='Dosya')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('tum', 'Tüm Sınıflar')], max_length=10, verbose_name='Sınıf')),
                ('yayin_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı (Ebelik)',
                'verbose_name_plural': 'Ders Programları (Ebelik)',
                'ordering': ['-yayin_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='DersProgramiDosyaEbelik',
        ),
        migrations.AlterModelOptions(
            name='ebelik_etkinlik',
            options={'ordering': ['baslangic_tarihi'], 'verbose_name': 'Etkinlik (Ebelik)', 'verbose_name_plural': 'Etkinlikler (Ebelik)'},
        ),
        migrations.AlterField(
            model_name='ebelik_etkinlik',
            name='afis',
            field=models.ImageField(blank=True, null=True, upload_to='etkinlikler/afis/ebelik/%Y/%m/%d/', verbose_name='Etkinlik Afişi'),
        ),
        migrations.AlterField(
            model_name='ebelik_etkinlik',
            name='etkinlik_turu',
            field=models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('tanitim', 'Tanıtım Günleri'), ('workshop', 'Workshop / Atölye'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü'),
        ),
    ]
