# Generated by Django 6.0 on 2026-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebelik', '0002_ebelikdersprogrami_delete_dersprogramidosyaebelik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbelikEtkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Etkinlik Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('kisa_aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('detayli_aciklama', models.TextField(verbose_name='Detaylı Açıklama')),
                ('etkinlik_turu', models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('tanitim', 'Tanıtım Günleri'), ('workshop', 'Workshop / Atölye'), ('sergi', 'Sergi'), ('yarisma', 'Yarışma'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('yer', models.CharField(max_length=255, verbose_name='Etkinlik Yeri')),
                ('afis', models.ImageField(blank=True, null=True, upload_to='etkinlikler/afis/ebelik/%Y/%m/%d/', verbose_name='Etkinlik Afişi')),
                ('katilim_linki', models.URLField(blank=True, verbose_name='Katılım Linki')),
                ('kayit_gerekiyor', models.BooleanField(default=False, verbose_name='Kayıt Gerekiyor')),
                ('ucretli', models.BooleanField(default=False, verbose_name='Ücretli Etkinlik')),
                ('yayinda', models.BooleanField(default=False, verbose_name='Yayında')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etkinlik (Ebelik)',
                'verbose_name_plural': 'Etkinlikler (Ebelik)',
                'ordering': ['baslangic_tarihi'],
            },
        ),
        migrations.DeleteModel(
            name='Ebelik_Etkinlik',
        ),
    ]
