# Generated by Django 6.0 on 2026-01-16 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulamali_bilimler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uygulamalibilimlerduyuru',
            name='kategori',
            field=models.CharField(choices=[('akademik', 'Akademik'), ('etkinlik', 'Etkinlik'), ('ogrenci', 'Öğrenci'), ('genel', 'Genel')], default='genel', max_length=20, verbose_name='Kategori'),
        ),
        migrations.CreateModel(
            name='UygulamaliBilimlerDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='uygulamali_bilimler/dosyalar/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(blank=True, max_length=255, verbose_name='Dosya Adı')),
                ('tur', models.CharField(choices=[('word', 'Word Belgesi'), ('pdf', 'PDF Belgesi'), ('excel', 'Excel Dosyası'), ('resim', 'Resim'), ('arsiv', 'Arşiv Dosyası'), ('diger', 'Diğer')], default='diger', max_length=10, verbose_name='Dosya Türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('duyuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='uygulamali_bilimler.uygulamalibilimlerduyuru', verbose_name='Duyuru')),
            ],
            options={
                'verbose_name': 'Uygulamalı Bilimler Dosyası',
                'verbose_name_plural': 'Uygulamalı Bilimler Dosyaları',
                'ordering': ['tur', 'dosya_adi'],
            },
        ),
    ]
