# Generated by Django 4.2.25 on 2025-11-03 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duyurular', '0004_bolum_duyuru_bolumler'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersProgramiDosyaMakineMuhendisligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Dosya Başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari_makine_muhendisligi/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_turu', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('resim', 'Resim'), ('diger', 'Diğer')], default='pdf', max_length=10, verbose_name='Dosya Türü')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('tum', 'Tüm Sınıflar'), ('lisansustu', 'Lisansüstü')], default='1', max_length=15, verbose_name='Sınıf')),
                ('akademik_yil', models.CharField(default='2024-2025', max_length=9, verbose_name='Akademik Yıl')),
                ('yayin_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı Dosyası (Makine Mühendisliği)',
                'verbose_name_plural': 'Ders Programı Dosyaları (Makine Mühendisliği)',
                'ordering': ['sira', '-yayin_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='MakineMuhendisligi_Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Etkinlik Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('kisa_aciklama', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('detayli_aciklama', models.TextField(verbose_name='Detaylı Açıklama')),
                ('etkinlik_turu', models.CharField(choices=[('konferans', 'Konferans / Kongre / Sempozyum'), ('seminer', 'Seminer / Panel'), ('kultur', 'Kültür-Sanat Etkinliği'), ('spor', 'Spor Etkinliği'), ('tanitim', 'Tanıtım Günleri'), ('workshop', 'Workshop / Atölye'), ('proje', 'Proje Yarışması'), ('teknik_gezi', 'Teknik Gezi'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Etkinlik Türü')),
                ('baslangic_tarihi', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('yer', models.CharField(max_length=255, verbose_name='Etkinlik Yeri')),
                ('afis', models.ImageField(blank=True, null=True, upload_to='etkinlikler/makine_muhendisligi/afis/%Y/%m/%d/', verbose_name='Etkinlik Afişi')),
                ('katilim_linki', models.URLField(blank=True, verbose_name='Katılım Linki')),
                ('kayit_gerekiyor', models.BooleanField(default=False, verbose_name='Kayıt Gerekiyor')),
                ('ucretli', models.BooleanField(default=False, verbose_name='Ücretli Etkinlik')),
                ('yayinda', models.BooleanField(default=False, verbose_name='Yayında')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Makine Mühendisliği Etkinliği',
                'verbose_name_plural': 'Makine Mühendisliği Etkinlikleri',
                'ordering': ['baslangic_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='MakineMuhendisligiDuyuru',
            fields=[
            ],
            options={
                'verbose_name': 'Makine Mühendisliği Duyurusu',
                'verbose_name_plural': 'Makine Mühendisliği Duyuruları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('duyurular.duyuru',),
        ),
    ]
