# Generated by Django 6.0 on 2026-08-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molekuler_biyoloji_genetik', '0003_molekulerbiyolojigenetiketkinlik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolekulerBiyolojiGenetikFaaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=300, verbose_name='Faaliyet Başlığı')),
                ('tarih', models.CharField(blank=True, max_length=100, verbose_name='Tarih / Dönem')),
                ('icerik', models.TextField(blank=True, verbose_name='İçerik')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Faaliyet (Molekuler Biyoloji Genetik)',
                'verbose_name_plural': 'Faaliyetler (Molekuler Biyoloji Genetik)',
                'ordering': ['sira', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MolekulerBiyolojiGenetikFaaliyetGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)')),
                ('faaliyet_turu', models.CharField(choices=[('idari', 'İdari Faaliyetler'), ('diger', 'Diğer Faaliyetler')], max_length=10, verbose_name='Faaliyet Türü')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Faaliyet Grubu (Molekuler Biyoloji Genetik)',
                'verbose_name_plural': 'Faaliyet Grupları (Molekuler Biyoloji Genetik)',
                'ordering': ['sira', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MolekulerBiyolojiGenetikFaaliyetGorseli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(upload_to='faaliyetler/molekuler_biyoloji_genetik/', verbose_name='Görsel')),
                ('sira', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('faaliyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorseller', to='molekuler_biyoloji_genetik.molekulerbiyolojigenetikfaaliyet', verbose_name='Faaliyet')),
            ],
            options={
                'verbose_name': 'Faaliyet Görseli (Molekuler Biyoloji Genetik)',
                'verbose_name_plural': 'Faaliyet Görselleri (Molekuler Biyoloji Genetik)',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.AddField(
            model_name='molekulerbiyolojigenetikfaaliyet',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faaliyetler', to='molekuler_biyoloji_genetik.molekulerbiyolojigenetikfaaliyetgrubu', verbose_name='Faaliyet Grubu'),
        ),
    ]
