# Generated by Django 4.2.25 on 2025-10-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdayIletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'Aday İletişim',
                'verbose_name_plural': 'Aday İletişimleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdayMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Menü Başlığı')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon Sınıfı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Aday Menü',
                'verbose_name_plural': 'Aday Menüler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdaySayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sayfa Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, upload_to='aday/', verbose_name='Görsel')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aday Sayfa',
                'verbose_name_plural': 'Aday Sayfalar',
            },
        ),
        migrations.CreateModel(
            name='AdaySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='aday/slider/', verbose_name='Slider Görseli')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Alt Başlık')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Buton Yazısı')),
                ('button_link', models.URLField(blank=True, verbose_name='Buton Linki')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Aday Slider',
                'verbose_name_plural': 'Aday Sliderlar',
                'ordering': ['order'],
            },
        ),
    ]
