# Generated by Django 4.2.25 on 2025-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aday_ogrenci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaysayfa',
            name='image',
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='excel_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='duyurular/excel/%Y/%m/%d/', verbose_name='Excel Dosyası'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='pdf_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='duyurular/pdf/%Y/%m/%d/', verbose_name='PDF Belgesi'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='word_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to='duyurular/word/%Y/%m/%d/', verbose_name='Word Belgesi'),
        ),
    ]
