# Generated by Django 4.2.25 on 2025-10-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aday_ogrenci', '0002_remove_adaysayfa_image_adaysayfa_excel_dosyasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaysayfa',
            name='excel_dosyasi',
        ),
        migrations.RemoveField(
            model_name='adaysayfa',
            name='pdf_dosyasi',
        ),
        migrations.RemoveField(
            model_name='adaysayfa',
            name='word_dosyasi',
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='image',
            field=models.ImageField(blank=True, upload_to='aday/', verbose_name='Görsel'),
        ),
    ]
