# Generated by Django 4.2.25 on 2025-10-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aday_ogrenci', '0003_remove_adaysayfa_excel_dosyasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaysayfa',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='aday/excel/', verbose_name='Excel Dosyası'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='other_file',
            field=models.FileField(blank=True, null=True, upload_to='aday/files/', verbose_name='Diğer Dosya'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='aday/pdf/', verbose_name='PDF Dosyası'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='aday/word/', verbose_name='Word Dosyası'),
        ),
    ]
