# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aday_ogrenci', '0004_adaysayfa_excel_file_adaysayfa_other_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaymenu',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Menü Başlığı'),
        ),
        migrations.AddField(
            model_name='adaymenu',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Menü Başlığı'),
        ),
        migrations.AddField(
            model_name='adaymenu',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Menü Başlığı'),
        ),
        migrations.AddField(
            model_name='adaymenu',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Menü Başlığı'),
        ),
        migrations.AddField(
            model_name='adaymenu',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Menü Başlığı'),
        ),
        migrations.AddField(
            model_name='adaymenu',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Menü Başlığı'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='content_de',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='content_en',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AddField(
            model_name='adaysayfa',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Sayfa Başlığı'),
        ),
        migrations.AddField(
            model_name='adayslider',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='adayslider',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='adayslider',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='adayslider',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='adayslider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='adayslider',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlık'),
        ),
    ]
