# Generated by Django 4.2.25 on 2025-10-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duyurular', '0004_bolum_duyuru_bolumler'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsikolojiDuyuru',
            fields=[
            ],
            options={
                'verbose_name': 'Psikoloji Duyurusu',
                'verbose_name_plural': 'Psikoloji Duyuruları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('duyurular.duyuru',),
        ),
    ]
