# Generated by Django 4.2.25 on 2025-10-27 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psikoloji', '0002_psi_etkinlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersProgramiDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Dosya Başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(upload_to='ders_programlari/%Y/%m/%d/', verbose_name='Dosya')),
                ('dosya_turu', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('resim', 'Resim'), ('diger', 'Diğer')], default='pdf', max_length=10, verbose_name='Dosya Türü')),
                ('sinif', models.CharField(choices=[('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('tum', 'Tüm Sınıflar'), ('lisansustu', 'Lisansüstü')], default='1', max_length=15, verbose_name='Sınıf')),
                ('akademik_yil', models.CharField(default='2024-2025', max_length=9, verbose_name='Akademik Yıl')),
                ('yayin_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Ders Programı Dosyası',
                'verbose_name_plural': 'Ders Programı Dosyaları',
                'ordering': ['sira', '-yayin_tarihi'],
            },
        ),
    ]
