# Generated by Django 6.0 on 2026-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocuk_gelisimi_programi', '0002_cocukgelisimiprogramifaaliyet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='baslik_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='baslik_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='baslik_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='baslik_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='baslik_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='cocukgelisimidersprogrami',
            name='baslik_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='baslik_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='baslik_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='baslik_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='baslik_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='baslik_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='baslik_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Etkinlik Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='detayli_aciklama_ar',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='detayli_aciklama_de',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='detayli_aciklama_en',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='detayli_aciklama_fa',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='detayli_aciklama_ru',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='detayli_aciklama_tr',
            field=models.TextField(null=True, verbose_name='Detaylı Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='kisa_aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='kisa_aciklama_de',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='kisa_aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='kisa_aciklama_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='kisa_aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimietkinlik',
            name='kisa_aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='baslik_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='Faaliyet Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='baslik_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Faaliyet Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='baslik_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Faaliyet Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='baslik_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='Faaliyet Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='baslik_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Faaliyet Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='baslik_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Faaliyet Başlığı'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='icerik_ar',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='icerik_de',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='icerik_en',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='icerik_fa',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='icerik_ru',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyet',
            name='icerik_tr',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyetgrubu',
            name='baslik_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyetgrubu',
            name='baslik_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyetgrubu',
            name='baslik_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyetgrubu',
            name='baslik_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyetgrubu',
            name='baslik_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)'),
        ),
        migrations.AddField(
            model_name='cocukgelisimiprogramifaaliyetgrubu',
            name='baslik_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Grup Başlığı (Örn: İdari Faaliyetler 2023-2024)'),
        ),
    ]
